### ISSUE TITLE
[suggestion] Integration with Obsidian

### ISSUE THREAD

**Issue by DenisVCode** [kaustubh-karkare/glados#2]
Hey, really cool project!

I would like to suggest integrating with [Obsidian.md](https://obsidian.md/), which could really help the adoption and allow easy integrations with other tools and plugins. 

Take care,
Denis

**Comment by kaustubh-karkare** [comment]
Thank you for the feedback and suggestion :)

* However, as far as I can tell, the Obsidian data model primarily corresponds to the concept of "Topics" in this app (although I don't have the fancy knowledge-graph visualization). However, it does not have anything like "Events" and "Structures" that I heavily use day to day.
* On the other hand, Obsidian has a more powerful text editor and allows images/etc, which this app does not yet support. Right now, sending data in either direction is going to be a lossy operation, so unless I'm missing something, I don't think we are quite ready for this yet.
